// Code generated by MockGen. DO NOT EDIT.
// Source: database.go

// Package database is a generated GoMock package.
package database

import (
	context "context"
	compute "inmem-db-go/internal/database/compute"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockcomputeLayer is a mock of computeLayer interface.
type MockcomputeLayer struct {
	ctrl     *gomock.Controller
	recorder *MockcomputeLayerMockRecorder
}

// MockcomputeLayerMockRecorder is the mock recorder for MockcomputeLayer.
type MockcomputeLayerMockRecorder struct {
	mock *MockcomputeLayer
}

// NewMockcomputeLayer creates a new mock instance.
func NewMockcomputeLayer(ctrl *gomock.Controller) *MockcomputeLayer {
	mock := &MockcomputeLayer{ctrl: ctrl}
	mock.recorder = &MockcomputeLayerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcomputeLayer) EXPECT() *MockcomputeLayerMockRecorder {
	return m.recorder
}

// HandleQuery mocks base method.
func (m *MockcomputeLayer) HandleQuery(arg0 context.Context, arg1 string) (compute.Query, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleQuery", arg0, arg1)
	ret0, _ := ret[0].(compute.Query)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleQuery indicates an expected call of HandleQuery.
func (mr *MockcomputeLayerMockRecorder) HandleQuery(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleQuery", reflect.TypeOf((*MockcomputeLayer)(nil).HandleQuery), arg0, arg1)
}

// MockstorageLayer is a mock of storageLayer interface.
type MockstorageLayer struct {
	ctrl     *gomock.Controller
	recorder *MockstorageLayerMockRecorder
}

// MockstorageLayerMockRecorder is the mock recorder for MockstorageLayer.
type MockstorageLayerMockRecorder struct {
	mock *MockstorageLayer
}

// NewMockstorageLayer creates a new mock instance.
func NewMockstorageLayer(ctrl *gomock.Controller) *MockstorageLayer {
	mock := &MockstorageLayer{ctrl: ctrl}
	mock.recorder = &MockstorageLayerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockstorageLayer) EXPECT() *MockstorageLayerMockRecorder {
	return m.recorder
}

// Del mocks base method.
func (m *MockstorageLayer) Del(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Del", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Del indicates an expected call of Del.
func (mr *MockstorageLayerMockRecorder) Del(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockstorageLayer)(nil).Del), ctx, key)
}

// Get mocks base method.
func (m *MockstorageLayer) Get(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockstorageLayerMockRecorder) Get(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockstorageLayer)(nil).Get), ctx, key)
}

// Set mocks base method.
func (m *MockstorageLayer) Set(ctx context.Context, key, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockstorageLayerMockRecorder) Set(ctx, key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockstorageLayer)(nil).Set), ctx, key, value)
}
